version: 2

sources:
  - name: erp_aw
    description: The sales data system of Adventure Works.
    database: FEA24_9  
    schema: RAW_ADVENTURE_WORKS
    tables:
      - name: product
        description: Source table with information about Adventure Works products.
        columns:
          - name: productid
            data_tests:
              - unique
              - not_null
      - name: address
        description: Source table with information about addresses.
        columns:
          - name: addressid
            data_tests:
              - unique
              - not_null
      - name: stateprovince
        description: Source table with information about states/provinces.
        columns:
          - name: stateprovinceid
            data_tests:
              - unique
              - not_null
      - name: countryregion
        description: Source table with information about countries.
        columns:
          - name: countryregioncode
            data_tests:
              - unique
              - not_null
      - name: customer
        description: Source table with information about customers.
        columns:
          - name: customerid
            data_tests:
              - unique
              - not_null
      - name: store
        description: Source table with information about stores.
        columns:
          - name: businessentityid
            data_tests:
              - unique
              - not_null
      - name: person
        description: Source table with information about persons.
        columns:
          - name: businessentityid
            data_tests:
              - unique
              - not_null
      - name: creditcard
        description: Source table with information about credit cards.
        columns:
          - name: creditcardid
            data_tests:
              - unique
              - not_null
      - name: salesorderheadersalesreason
        description: Source table with information about sales order reasons keys.
        columns:
          - name: salesorderid
            data_tests:
              - not_null
      - name: salesreason
        description: Source table with information about sales order reasons.
        columns:
          - name: salesreasonid
            data_tests:
              - unique
              - not_null
      - name: salesorderdetail
        description: Source table with information about sales orders details.
        columns:
          - name: salesorderdetailid
            data_tests:
              - unique
              - not_null
      - name: salesorderheader
        description: Source table with information about sales orders.
        columns:
          - name: salesorderid
            data_tests:
              - unique
              - not_null
      - name: productsubcategory
        description: Source table with information about products subcategories.
        columns:
          - name: productsubcategoryid
            data_tests:
              - unique
              - not_null
      - name: productcategory
        description: Source table with information about products categories.
        columns:
          - name: productcategoryid
            data_tests:
              - unique
              - not_null
